### ISSUE TITLE
AWS S3 object key format documentation

### ISSUE THREAD

**Issue by onefuncman** [michaelbrewer/aws-lambda-events#2]
Hi,

this seems like a reasonable project to document that s3.object.key in https://github.com/michaelbrewer/aws-lambda-events/blob/main/docs/s3.md is a URI fragment that is URL-encoded.  One consequence is that in order to retrieve an object given this s3.object.key you have to urldecode the value to pass back into the S3 APIs as they will attempt to urlencode them.  This is very notable when dealing with filenames with pluses in them, like c++ linux packages or parens like you will see from `(1) copy` from files uploaded from end users computers.

I'm not sure the best way to document these kinds of exceptional embedded meanings though

**Comment by michaelbrewer** [comment]
Possibly via use cases. Let me have a deeper look

**Comment by michaelbrewer** [comment]
I did come across this when working on AWS Lambda Powertools for Python, so i have updated the docs to include a tip on this. I will still need to expand on the either fields too.

See the latest version: https://michaelbrewer.github.io/aws-lambda-events/s3/

**Comment by onefuncman** [comment]
Nice! That set of changes culminating in 7f681fb9cfb292b7f64026a67590e117c80a75af resolves this issue from my POV, so I'll close this.
